name: Build 
on:
  push:
    branches:
      - test
jobs:
  build:
    runs-on: macos-latest
    env:
      THEOS: theos
    steps:
        - name: Xcode Setup
          uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: latest-stable
        
        - name: Checkout
          uses: actions/checkout@master
          with:
              submodules: recursive
        
        - name: Install Procursus
          uses: dhinakg/procursus-action@main
          with:
            packages: ldid findutils sed coreutils make
        
        - name: Install better GNU Make
          run: |
            brew install make
            echo "PATH=$(brew --prefix make)/libexec/gnubin:$PATH" >> $GITHUB_ENV
            
        - name: Install THEOS
          run: |
            set -x
            export BASEDIR="$(pwd)"
            export THEOS="${BASEDIR}/theos"
            mkdir -p $THEOS
            curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos >> install-theos.sh
            gsed -E "/^\s*get_theos\s*$/,+1 s/^(\s*)(get_sdks)\s*$/\1mkdir -p \${THEOS}\/sdks\n\1touch \${THEOS}\/sdks\/sdk\n\1\2/g" -i install-theos.sh
            bash install-theos.sh
            curl -L https://github.com/theos/sdks/releases/latest/download/iPhoneOS16.5.sdk.tar.xz --output $THEOS/sdks/iPhoneOS16.5.sdk.tar.xz
            gunzip $THEOS/sdks/iPhoneOS16.5.sdk.tar.xz
            tar -xf $THEOS/sdks/iPhoneOS16.5.sdk.tar -C $THEOS/sdks
            rm $THEOS/sdks/iPhoneOS16.5.sdk.tar
            cd $BASEDIR
            
        - name: Build Package
          id: build_package
          run: |
            make package FINALPACKAGE=1
            echo "::set-output name=package::$(ls -t packages | head -n1)"
            
        - name: Upload Artifact
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}          
            asset_path: ./packages/${{ steps.build_package.outputs.package }}
            asset_name: ${{ steps.build_package.outputs.package }}
            asset_content_type: application/vnd.debian.binary-package